### ISSUE TITLE
Tables might be broken?

### ISSUE THREAD

**Issue by throwaway-a** [citynetwork/markdown-xblock#22]
When I put in 

```
| Syntax      | Description |
| ----------- | ----------- |
| Header      | Title       |
| Paragraph   | Text        |
```

to a markdown box in open edx, while it does turn into a roughly space-deliminated table-looking thing, there doesn't appear to be any bars between table entries like I would expect. (And like I see here on github apparently.) Is this your expectation as well?

**Comment by mrtmm** [comment]
Closing this, as tables are not really _broken_.

Additionally, in the linked PR #26, we added some basic CSS to match the tables to the current raw-HTML XBlock tables but it's possible to style it to your liking via custom theme/brand.

To get a table that looks like the one in the above comment, you'll need to use code formatting (much like you do here in GitHub), for example, if you add the following in Studio:
<img width="242" alt="Screen Shot 2022-07-21 at 14 12 27" src="https://user-images.githubusercontent.com/56252537/180201956-e1ce1daa-5eb2-4633-bd07-ff3a59850e05.png">
you'll see the following in the LMS:
<img width="1095" alt="Screen Shot 2022-07-21 at 14 12 15" src="https://user-images.githubusercontent.com/56252537/180202044-a5345f88-34cc-44c8-a7e6-a06435844288.png">

I hope this helps!

**Comment by throwaway-a** [comment]
Confirmed this worked for me. Thanks!
