### ISSUE TITLE
Code blocks with bash formatting specified cause breakage of entire unit without ability to recover

### ISSUE THREAD

**Issue by throwaway-a** [citynetwork/markdown-xblock#30]
If I use
```
-```bash
-```
```
(Remove the -, I just don't know how to write the code block syntax within a code block without it prematurely ending it)
This causes the following error to appear

![image](https://user-images.githubusercontent.com/77025740/171437761-ac37c8ad-285b-4a1c-92ca-9985761248f5.png)

If I then reload the page, there's no more capability to add/remove components from the unit, so there's no recourse except to delete the entire unit.

**Comment by mrtmm** [comment]
@throwaway-a thanks for the report. This is long overdue but I have been trying to reproduce this issue now, however with no luck.

Code blocks (with or without `bash`) seem to work fine for me. Even when I removed `code-friendly` and `fenced-code-blocks` from the `extras` it does not break the component as you described.

I acknowledge that this was reported a while ago; if you are still running into this issue please share more information about your setup and configurations and I'll try to reproduce the it.

**Comment by fghaas** [comment]
Closing this issue after a month of inactivity since we have reason to believe that the XBlock is working correctly (at least in its current releases). If this issue resurfaces, please comment here and we'll reopen.
