### ISSUE TITLE
Doesn't work with tutor 17.0.0 / Open EdX Quince?

### ISSUE THREAD

**Issue by throwaway-a** [citynetwork/markdown-xblock#35]
I have a brand new fresh install of Quince / tutor 17.0.0. I did `pip install markdown-xblock==1.3.0`. I re-launched Open edX with "tutor local launch". I imported a class from an older instance that used Markdown. However, I don't see the Markdown option under the Advanced component adding button anymore, nor do I see the the existing Markdown blocks in the imported class.

I suspect this needs an update to support Quince?

**Comment by fghaas** [comment]
And update to the README just landed in #36. The [Installation with Tutor](https://github.com/citynetwork/markdown-xblock#installation-with-tutor) section should now better explain how to bake the XBlock into the Tutor `openedx` Docker image.

**Comment by waza-ari** [comment]
We're using it with Quince, so yes, it's working. There's a bunch of deprecation warnings as follows, but it does work:

```
2024-01-25 16:52:44,537 WARNING 353 [py.warnings] [user None] [ip None] warnings.py:109 - /openedx/venv/lib/python3.8/site-packages/markdown_xblock/html.py:14: DeprecatedPackageWarning: Please use import xblock.utils.settings instead of xblockutils.settings because the 'xblock-utils' package has been deprecated and migrated to within 'xblock' package. 
  from xblockutils.settings import XBlockWithSettingsMixin
```

I'll open a separate issue for that.

**Comment by fghaas** [comment]
@waza-ari Thanks for confirming that it does work on Quince; I'll close _this_ issue now and we'll look into #38 separately.
