### ISSUE TITLE
Code blocks show up as grey in editing view but not published view

### ISSUE THREAD

**Issue by throwaway-a** [citynetwork/markdown-xblock#42]
When I add code like this:

![image](https://github.com/citynetwork/markdown-xblock/assets/77025740/6df05ed7-37e2-474c-ae00-f0232674329b)

It looks like this in the editing view:

![image](https://github.com/citynetwork/markdown-xblock/assets/77025740/aa58910a-081a-4dcb-a069-b17ac7aefe90)

But students see this:
![image](https://github.com/citynetwork/markdown-xblock/assets/77025740/317c8739-d16c-4a6d-a564-2a096382b907)

So the text is mono-space, but not grey. I'd like it to appear grey for the published view so it stands out.

I have the following tutor plugin to enable extras, but it still doesn't make things grey.
```
name: disable_markdown_safemode
version: 0.1.0
patches:
  openedx-common-settings: |
    XBLOCK_SETTINGS["markdown"] = {
    "extras": [
        "code-friendly",
        "fenced-code-blocks",
        "footnotes",
        "tables",
        "header-ids",
        "pyshell",
        "smarty-pants",
        "strike",
        "target-blank-links",
        "use-file-vars",
        "wiki-tables",
        "tag-friendly"
    ],
    'safe_mode': False
    }
```

Is there another extra that can be enabled to achieve this?

(p.s. if the answer is something to do with CSS, can you provide some guidance on that? Because I don't know how to edit CSS in tutor-based Open edX.)

**Comment by mrtmm** [comment]
I believe this is mostly about adding custom styling to your theme with CSS changes.

I replied to a forum post that links back to this issue with an example how to do so using the [tutor-indigo](https://github.com/overhangio/tutor-indigo) theme: https://discuss.openedx.org/t/markdown-code-blocks-show-up-as-grey-on-editing-page-but-not-published-page/12918
